import sys, fileinput, os, re, linecache, random

# INSTRUCTIONS:
#   1. Flip all Cards to the Kanji_Back+Front and Back-Front Note types
#   2. Export the Japanese::Export::1 deck and Japanese::Export::2 deck to: Users/Jonathan/Git/learning_material/python
#   3. cd to the Users/Jonathan/Git/learning_material/python directory
#   4. Run: python3 conjugate.py [number]
#       number = the number of conjugated words to select at random

number_of_lines = 0

# Read from Japanese__Export__1.txt file
j_exp_file = open('Japanese__Export__1.txt', 'r')
file_content = j_exp_file.read()
lines = file_content.split('\n')
j_exp_file.close()

# Mode 'w' overrites whatever's in there already
with open('conjugated.txt', 'w') as file:
    for line in lines:
        if re.search("^.+\t", line):
            word = re.findall("^.+\t", line)[0][0:-1]
            if word[-1] == 'い':
                file.write(word[:-1] + 'くて' + '\n')
                file.write(word + '\n')
                file.write(word + 'です' + '\n')
                file.write(word[:-1] + 'くない' + '\n')
                file.write(word[:-1] + 'くありません' + '\n')
                file.write(word[:-1] + 'かった' + '\n')
                file.write(word[:-1] + 'かったです' + '\n')
                file.write(word[:-1] + 'くなかった' + '\n')
                file.write(word[:-1] + 'くありませんでした' + '\n')
                file.write(word[:-1] + 'く' + '\n')
            elif word[-3:] == '[な]':
                file.write(word[:-3] + 'で' + '\n')
                file.write(word[:-3] + 'だ' + '\n')
                file.write(word[:-3] + 'です' + '\n')
                file.write(word[:-3] + 'でわない' + '\n')
                file.write(word[:-3] + 'でわありません' + '\n')
                file.write(word[:-3] + 'だった' + '\n')
                file.write(word[:-3] + 'でした' + '\n')
                file.write(word[:-3] + 'でわなかった' + '\n')
                file.write(word[:-3] + 'でわありませんでした' + '\n')
                file.write(word[:-3] + '\n')
                file.write(word[:-3] + 'に' + '\n')
            elif word[-4:] == '[する]':
                file.write(word[:-4] + 'して' + '\n')
                file.write(word[:-4] + 'してなきゃ' + '\n')
                file.write(word[:-4] + 'しても' + '\n')
                file.write(word[:-4] + 'してくれる' + '\n')
                file.write(word[:-4] + 'してくれませんか' + '\n')
                file.write(word[:-4] + 'してもいいですか' + '\n')
                file.write(word[:-4] + 'してはいけない' + '\n')
                file.write(word[:-4] + 'してはいけません' + '\n')
                file.write(word[:-4] + 'する' + '\n')
                file.write(word[:-4] + 'します' + '\n')
                file.write(word[:-4] + 'しない' + '\n')
                file.write(word[:-4] + 'しません' + '\n')
                file.write(word[:-4] + 'した' + '\n')
                file.write(word[:-4] + 'しました' + '\n')
                file.write(word[:-4] + 'しなかった' + '\n')
                file.write(word[:-4] + 'しませんでした' + '\n')
                file.write(word[:-4] + 'している' + '\n')
                file.write(word[:-4] + 'してる' + '\n')
                file.write(word[:-4] + 'しています' + '\n')
                file.write(word[:-4] + 'してます' + '\n')
                file.write(word[:-4] + 'していない' + '\n')
                file.write(word[:-4] + 'してない' + '\n')
                file.write(word[:-4] + 'していません' + '\n')
                file.write(word[:-4] + 'してません' + '\n')
                file.write(word[:-4] + 'していた' + '\n')
                file.write(word[:-4] + 'してた' + '\n')
                file.write(word[:-4] + 'していました' + '\n')
                file.write(word[:-4] + 'してました' + '\n')
                file.write(word[:-4] + 'していなかった' + '\n')
                file.write(word[:-4] + 'してなかった' + '\n')
                file.write(word[:-4] + 'していませんでした' + '\n')
                file.write(word[:-4] + 'してませんでした' + '\n')
                file.write(word[:-4] + 'し' + '\n')
                file.write(word[:-4] + 'したい' + '\n')
                file.write(word[:-4] + 'しよう' + '\n')
                file.write(word[:-4] + 'しましょう' + '\n')
                file.write(word[:-4] + 'しないだろう' + '\n')
                file.write(word[:-4] + 'しないでしょう' + '\n')
                file.write(word[:-4] + 'したろう' + '\n')
                file.write(word[:-4] + 'しましたろう' + '\n')
                file.write(word[:-4] + 'しなかっただろう' + '\n')
                file.write(word[:-4] + 'しなかったでしょう' + '\n')
                file.write(word[:-4] + 'してください' + '\n')
                file.write(word[:-4] + 'しないでください' + '\n')
                file.write(word[:-4] + 'させる' + '\n')
                file.write(word[:-4] + 'させます' + '\n')
                file.write(word[:-4] + 'させない' + '\n')
                file.write(word[:-4] + 'させません' + '\n')
                file.write(word[:-4] + 'したら' + '\n')
                file.write(word[:-4] + 'しましたら' + '\n')
                file.write(word[:-4] + 'しなかったら' + '\n')
                file.write(word[:-4] + 'しませんでしたら' + '\n')
                file.write(word[:-4] + 'しなければ' + '\n')
                file.write(word[:-4] + 'すれば' + '\n')
                file.write(word[:-4] + 'しますれば' + '\n')
                file.write(word[:-4] + 'させられる' + '\n')
                file.write(word[:-4] + 'させられた' + '\n')
                file.write(word[:-4] + 'される' + '\n')
                file.write(word[:-4] + 'するな' + '\n')
                file.write(word[:-4] + 'しろ' + '\n')
                file.write(word[:-4] + 'しなさい' + '\n')
                file.write(word[:-4] + 'できない' + '\n')
                file.write(word[:-4] + 'できません' + '\n')
                file.write(word[:-4] + 'できる' + '\n')
                file.write(word[:-4] + 'できます' + '\n')
            elif word[-4:] == '[くる]':
                file.write(word[:-4] + '来て' + '\n')
                file.write(word[:-4] + '来てなきゃ' + '\n')
                file.write(word[:-4] + '来ても' + '\n')
                file.write(word[:-4] + '来てくれる' + '\n')
                file.write(word[:-4] + '来てくれませんか' + '\n')
                file.write(word[:-4] + '来てもいいですか' + '\n')
                file.write(word[:-4] + '来てはいけない' + '\n')
                file.write(word[:-4] + '来てはいけません' + '\n')
                file.write(word[:-4] + '来る' + '\n')
                file.write(word[:-4] + '来ます' + '\n')
                file.write(word[:-4] + '来ない' + '\n')
                file.write(word[:-4] + '来ません' + '\n')
                file.write(word[:-4] + '来た' + '\n')
                file.write(word[:-4] + '来ました' + '\n')
                file.write(word[:-4] + '来なかった' + '\n')
                file.write(word[:-4] + '来ませんでした' + '\n')
                file.write(word[:-4] + '来ている' + '\n')
                file.write(word[:-4] + '来てる' + '\n')
                file.write(word[:-4] + '来ています' + '\n')
                file.write(word[:-4] + '来てます' + '\n')
                file.write(word[:-4] + '来ていない' + '\n')
                file.write(word[:-4] + '来てない' + '\n')
                file.write(word[:-4] + '来ていません' + '\n')
                file.write(word[:-4] + '来てません' + '\n')
                file.write(word[:-4] + '来ていた' + '\n')
                file.write(word[:-4] + '来てた' + '\n')
                file.write(word[:-4] + '来ていました' + '\n')
                file.write(word[:-4] + '来てました' + '\n')
                file.write(word[:-4] + '来ていなかった' + '\n')
                file.write(word[:-4] + '来てなかった' + '\n')
                file.write(word[:-4] + '来ていませんでした' + '\n')
                file.write(word[:-4] + '来てませんでした' + '\n')
                file.write(word[:-4] + '来' + '\n')
                file.write(word[:-4] + '来たい' + '\n')
                file.write(word[:-4] + '来よう' + '\n')
                file.write(word[:-4] + '来ましょう' + '\n')
                file.write(word[:-4] + '来ないだろう' + '\n')
                file.write(word[:-4] + '来ないでしょう' + '\n')
                file.write(word[:-4] + '来たでしょう' + '\n')
                file.write(word[:-4] + '来なかっただろう' + '\n')
                file.write(word[:-4] + '来なかったでしょう' + '\n')
                file.write(word[:-4] + '来てください' + '\n')
                file.write(word[:-4] + '来ないでください' + '\n')
                file.write(word[:-4] + '来させる' + '\n')
                file.write(word[:-4] + '来させます' + '\n')
                file.write(word[:-4] + '来させない' + '\n')
                file.write(word[:-4] + '来させません' + '\n')
                file.write(word[:-4] + '来たら' + '\n')
                file.write(word[:-4] + '来ましたら' + '\n')
                file.write(word[:-4] + '来れば' + '\n')
                file.write(word[:-4] + '来ますれば' + '\n')
                file.write(word[:-4] + '来なければ' + '\n')
                file.write(word[:-4] + '来させられる' + '\n')
                file.write(word[:-4] + '来させられた' + '\n')
                file.write(word[:-4] + '来られる' + '\n')
                file.write(word[:-4] + '来られます' + '\n')
                file.write(word[:-4] + '来るな' + '\n')
                file.write(word[:-4] + '来い' + '\n')
                file.write(word[:-4] + '来なさい' + '\n')
                file.write(word[:-4] + '来られない' + '\n')
                file.write(word[:-4] + '来られません' + '\n')
            elif word == 'する':
                file.write('して' + '\n')
                file.write('してなきゃ' + '\n')
                file.write('しても' + '\n')
                file.write('してくれる' + '\n')
                file.write('してくれませんか' + '\n')
                file.write('してもいいですか' + '\n')
                file.write('してはいけない' + '\n')
                file.write('してはいけません' + '\n')
                file.write('する' + '\n')
                file.write('します' + '\n')
                file.write('しない' + '\n')
                file.write('しません' + '\n')
                file.write('した' + '\n')
                file.write('しました' + '\n')
                file.write('しなかった' + '\n')
                file.write('しませんでした' + '\n')
                file.write('している' + '\n')
                file.write('してる' + '\n')
                file.write('しています' + '\n')
                file.write('してます' + '\n')
                file.write('していない' + '\n')
                file.write('してない' + '\n')
                file.write('していません' + '\n')
                file.write('してません' + '\n')
                file.write('していた' + '\n')
                file.write('してた' + '\n')
                file.write('していました' + '\n')
                file.write('してました' + '\n')
                file.write('していなかった' + '\n')
                file.write('してなかった' + '\n')
                file.write('していませんでした' + '\n')
                file.write('してませんでした' + '\n')
                file.write('し' + '\n')
                file.write('したい' + '\n')
                file.write('しよう' + '\n')
                file.write('しましょう' + '\n')
                file.write('しないだろう' + '\n')
                file.write('しないでしょう' + '\n')
                file.write('したろう' + '\n')
                file.write('しましたろう' + '\n')
                file.write('しなかっただろう' + '\n')
                file.write('しなかったでしょう' + '\n')
                file.write('してください' + '\n')
                file.write('しないでください' + '\n')
                file.write('させる' + '\n')
                file.write('させます' + '\n')
                file.write('させない' + '\n')
                file.write('させません' + '\n')
                file.write('したら' + '\n')
                file.write('しましたら' + '\n')
                file.write('しなかったら' + '\n')
                file.write('しませんでしたら' + '\n')
                file.write('しなければ' + '\n')
                file.write('すれば' + '\n')
                file.write('しますれば' + '\n')
                file.write('させられる' + '\n')
                file.write('させられた' + '\n')
                file.write('される' + '\n')
                file.write('するな' + '\n')
                file.write('しろ' + '\n')
                file.write('しなさい' + '\n')
                file.write('できない' + '\n')
                file.write('できません' + '\n')
                file.write('できる' + '\n')
                file.write('できます' + '\n')
            elif word == '来る':
                file.write('来て' + '\n')
                file.write('来てなきゃ' + '\n')
                file.write('来ても' + '\n')
                file.write('来てくれる' + '\n')
                file.write('来てくれませんか' + '\n')
                file.write('来てもいいですか' + '\n')
                file.write('来てはいけない' + '\n')
                file.write('来てはいけません' + '\n')
                file.write('来る' + '\n')
                file.write('来ます' + '\n')
                file.write('来ない' + '\n')
                file.write('来ません' + '\n')
                file.write('来た' + '\n')
                file.write('来ました' + '\n')
                file.write('来なかった' + '\n')
                file.write('来ませんでした' + '\n')
                file.write('来ている' + '\n')
                file.write('来てる' + '\n')
                file.write('来ています' + '\n')
                file.write('来てます' + '\n')
                file.write('来ていない' + '\n')
                file.write('来てない' + '\n')
                file.write('来ていません' + '\n')
                file.write('来てません' + '\n')
                file.write('来ていた' + '\n')
                file.write('来てた' + '\n')
                file.write('来ていました' + '\n')
                file.write('来てました' + '\n')
                file.write('来ていなかった' + '\n')
                file.write('来てなかった' + '\n')
                file.write('来ていませんでした' + '\n')
                file.write('来てませんでした' + '\n')
                file.write('来' + '\n')
                file.write('来たい' + '\n')
                file.write('来よう' + '\n')
                file.write('来ましょう' + '\n')
                file.write('来ないだろう' + '\n')
                file.write('来ないでしょう' + '\n')
                file.write('来たでしょう' + '\n')
                file.write('来なかっただろう' + '\n')
                file.write('来なかったでしょう' + '\n')
                file.write('来てください' + '\n')
                file.write('来ないでください' + '\n')
                file.write('来させる' + '\n')
                file.write('来させます' + '\n')
                file.write('来させない' + '\n')
                file.write('来させません' + '\n')
                file.write('来たら' + '\n')
                file.write('来ましたら' + '\n')
                file.write('来れば' + '\n')
                file.write('来ますれば' + '\n')
                file.write('来なければ' + '\n')
                file.write('来させられる' + '\n')
                file.write('来させられた' + '\n')
                file.write('来られる' + '\n')
                file.write('来られます' + '\n')
                file.write('来るな' + '\n')
                file.write('来い' + '\n')
                file.write('来なさい' + '\n')
                file.write('来られない' + '\n')
                file.write('来られません' + '\n')
            elif word[-1] == 'う':
                file.write(word[:-1] + 'って' + '\n')
                file.write(word[:-1] + 'ってなきゃ' + '\n')
                file.write(word[:-1] + 'っても' + '\n')
                file.write(word[:-1] + 'ってくれる' + '\n')
                file.write(word[:-1] + 'ってくれませんか' + '\n')
                file.write(word[:-1] + 'ってもいいですか' + '\n')
                file.write(word[:-1] + 'ってはいけない' + '\n')
                file.write(word[:-1] + 'ってはいけません' + '\n')
                file.write(word + '\n')
                file.write(word[:-1] + 'います' + '\n')
                file.write(word[:-1] + 'いません' + '\n')
                file.write(word[:-1] + 'わない' + '\n')
                file.write(word[:-1] + 'った' + '\n')
                file.write(word[:-1] + 'いました' + '\n')
                file.write(word[:-1] + 'いませんでした' + '\n')
                file.write(word[:-1] + 'わなかった' + '\n')
                file.write(word[:-1] + 'っている' + '\n')
                file.write(word[:-1] + 'ってる' + '\n')
                file.write(word[:-1] + 'っています' + '\n')
                file.write(word[:-1] + 'ってます' + '\n')
                file.write(word[:-1] + 'っていない' + '\n')
                file.write(word[:-1] + 'ってない' + '\n')
                file.write(word[:-1] + 'っていません' + '\n')
                file.write(word[:-1] + 'ってません' + '\n')
                file.write(word[:-1] + 'っていた' + '\n')
                file.write(word[:-1] + 'ってた' + '\n')
                file.write(word[:-1] + 'っていました' + '\n')
                file.write(word[:-1] + 'ってました' + '\n')
                file.write(word[:-1] + 'っていなかった' + '\n')
                file.write(word[:-1] + 'ってなかった' + '\n')
                file.write(word[:-1] + 'っていませんでした' + '\n')
                file.write(word[:-1] + 'ってませんでした' + '\n')
                file.write(word[:-1] + 'い' + '\n')
                file.write(word[:-1] + 'いたい' + '\n')
                file.write(word[:-1] + 'おう' + '\n')
                file.write(word[:-1] + 'いましょう' + '\n')
                file.write(word[:-1] + 'わないだろう' + '\n')
                file.write(word[:-1] + 'わないでしょう' + '\n')
                file.write(word[:-1] + 'ったろう' + '\n')
                file.write(word[:-1] + 'ったでしょう' + '\n')
                file.write(word[:-1] + 'わなかっただろう' + '\n')
                file.write(word[:-1] + 'わなかったでしょう' + '\n')
                file.write(word[:-1] + 'ってください' + '\n')
                file.write(word[:-1] + 'わないでください' + '\n')
                file.write(word[:-1] + 'わせる' + '\n')
                file.write(word[:-1] + 'わせます' + '\n')
                file.write(word[:-1] + 'わせない' + '\n')
                file.write(word[:-1] + 'わせません' + '\n')
                file.write(word[:-1] + 'ったら' + '\n')
                file.write(word[:-1] + 'いましたら' + '\n')
                file.write(word[:-1] + 'わなかったら' + '\n')
                file.write(word[:-1] + 'いませんでしたら' + '\n')
                file.write(word[:-1] + 'えば' + '\n')
                file.write(word[:-1] + 'わなければ' + '\n')
                file.write(word[:-1] + 'わせられる' + '\n')
                file.write(word[:-1] + 'わせられた' + '\n')
                file.write(word[:-1] + 'われる' + '\n')
                file.write(word[:-1] + 'われます' + '\n')
                file.write(word[:-1] + 'われない' + '\n')
                file.write(word[:-1] + 'われません' + '\n')
                file.write(word + 'な' + '\n')
                file.write(word[:-1] + 'え' + '\n')
                file.write(word[:-1] + 'いなさい' + '\n')
                file.write(word[:-1] + 'えない' + '\n')
                file.write(word[:-1] + 'えません' + '\n')
                file.write(word[:-1] + 'える' + '\n')
                file.write(word[:-1] + 'えます' + '\n')
            elif word[-1] == 'つ':
                file.write(word[:-1] + 'って' + '\n')
                file.write(word[:-1] + 'ってなきゃ' + '\n')
                file.write(word[:-1] + 'っても' + '\n')
                file.write(word[:-1] + 'ってくれる' + '\n')
                file.write(word[:-1] + 'ってくれませんか' + '\n')
                file.write(word[:-1] + 'ってもいいですか' + '\n')
                file.write(word[:-1] + 'ってはいけない' + '\n')
                file.write(word[:-1] + 'ってはいけません' + '\n')
                file.write(word + '\n')
                file.write(word[:-1] + 'ちます' + '\n')
                file.write(word[:-1] + 'ちません' + '\n')
                file.write(word[:-1] + 'たない' + '\n')
                file.write(word[:-1] + 'った' + '\n')
                file.write(word[:-1] + 'ちました' + '\n')
                file.write(word[:-1] + 'ちませんでした' + '\n')
                file.write(word[:-1] + 'たなかった' + '\n')
                file.write(word[:-1] + 'っている' + '\n')
                file.write(word[:-1] + 'ってる' + '\n')
                file.write(word[:-1] + 'っています' + '\n')
                file.write(word[:-1] + 'ってます' + '\n')
                file.write(word[:-1] + 'っていない' + '\n')
                file.write(word[:-1] + 'ってない' + '\n')
                file.write(word[:-1] + 'っていません' + '\n')
                file.write(word[:-1] + 'ってません' + '\n')
                file.write(word[:-1] + 'っていた' + '\n')
                file.write(word[:-1] + 'ってた' + '\n')
                file.write(word[:-1] + 'っていました' + '\n')
                file.write(word[:-1] + 'ってました' + '\n')
                file.write(word[:-1] + 'っていなかった' + '\n')
                file.write(word[:-1] + 'ってなかった' + '\n')
                file.write(word[:-1] + 'っていませんでした' + '\n')
                file.write(word[:-1] + 'ってませんでした' + '\n')
                file.write(word[:-1] + 'ち' + '\n')
                file.write(word[:-1] + 'ちたい' + '\n')
                file.write(word[:-1] + 'とう' + '\n')
                file.write(word[:-1] + 'ちましょう' + '\n')
                file.write(word[:-1] + 'たないだろう' + '\n')
                file.write(word[:-1] + 'たないでしょう' + '\n')
                file.write(word[:-1] + 'ったろう' + '\n')
                file.write(word[:-1] + 'ったでしょう' + '\n')
                file.write(word[:-1] + 'たなかっただろう' + '\n')
                file.write(word[:-1] + 'たなかったでしょう' + '\n')
                file.write(word[:-1] + 'ってください' + '\n')
                file.write(word[:-1] + 'たないでください' + '\n')
                file.write(word[:-1] + 'たせる' + '\n')
                file.write(word[:-1] + 'たせます' + '\n')
                file.write(word[:-1] + 'たせない' + '\n')
                file.write(word[:-1] + 'たせません' + '\n')
                file.write(word[:-1] + 'ったら' + '\n')
                file.write(word[:-1] + 'ちましたら' + '\n')
                file.write(word[:-1] + 'たなかったら' + '\n')
                file.write(word[:-1] + 'ちませんでしたら' + '\n')
                file.write(word[:-1] + 'てば' + '\n')
                file.write(word[:-1] + 'たなければ' + '\n')
                file.write(word[:-1] + 'たせられる' + '\n')
                file.write(word[:-1] + 'たせられた' + '\n')
                file.write(word[:-1] + 'たれる' + '\n')
                file.write(word[:-1] + 'たれます' + '\n')
                file.write(word[:-1] + 'たれない' + '\n')
                file.write(word[:-1] + 'たれません' + '\n')
                file.write(word + 'な' + '\n')
                file.write(word[:-1] + 'て' + '\n')
                file.write(word[:-1] + 'ちなさい' + '\n')
                file.write(word[:-1] + 'てない' + '\n')
                file.write(word[:-1] + 'てません' + '\n')
                file.write(word[:-1] + 'てる' + '\n')
                file.write(word[:-1] + 'てます' + '\n')
            elif word[-1] == 'る':
                file.write(word[:-1] + 'って' + '\n')
                file.write(word[:-1] + 'ってなきゃ' + '\n')
                file.write(word[:-1] + 'っても' + '\n')
                file.write(word[:-1] + 'ってくれる' + '\n')
                file.write(word[:-1] + 'ってくれませんか' + '\n')
                file.write(word[:-1] + 'ってもいいですか' + '\n')
                file.write(word[:-1] + 'ってはいけない' + '\n')
                file.write(word[:-1] + 'ってはいけません' + '\n')
                file.write(word + '\n')
                file.write(word[:-1] + 'ります' + '\n')
                file.write(word[:-1] + 'りません' + '\n')
                file.write(word[:-1] + 'らない' + '\n')
                file.write(word[:-1] + 'った' + '\n')
                file.write(word[:-1] + 'りました' + '\n')
                file.write(word[:-1] + 'りませんでした' + '\n')
                file.write(word[:-1] + 'らなかった' + '\n')
                file.write(word[:-1] + 'っている' + '\n')
                file.write(word[:-1] + 'ってる' + '\n')
                file.write(word[:-1] + 'っています' + '\n')
                file.write(word[:-1] + 'ってます' + '\n')
                file.write(word[:-1] + 'っていない' + '\n')
                file.write(word[:-1] + 'ってない' + '\n')
                file.write(word[:-1] + 'っていません' + '\n')
                file.write(word[:-1] + 'ってません' + '\n')
                file.write(word[:-1] + 'っていた' + '\n')
                file.write(word[:-1] + 'ってた' + '\n')
                file.write(word[:-1] + 'っていました' + '\n')
                file.write(word[:-1] + 'ってました' + '\n')
                file.write(word[:-1] + 'っていなかった' + '\n')
                file.write(word[:-1] + 'ってなかった' + '\n')
                file.write(word[:-1] + 'っていませんでした' + '\n')
                file.write(word[:-1] + 'ってませんでした' + '\n')
                file.write(word[:-1] + 'り' + '\n')
                file.write(word[:-1] + 'りたい' + '\n')
                file.write(word[:-1] + 'ろう' + '\n')
                file.write(word[:-1] + 'りましょう' + '\n')
                file.write(word[:-1] + 'らないだろう' + '\n')
                file.write(word[:-1] + 'らないでしょう' + '\n')
                file.write(word[:-1] + 'ったろう' + '\n')
                file.write(word[:-1] + 'ったでしょう' + '\n')
                file.write(word[:-1] + 'らなかっただろう' + '\n')
                file.write(word[:-1] + 'らなかったでしょう' + '\n')
                file.write(word[:-1] + 'ってください' + '\n')
                file.write(word[:-1] + 'らないでください' + '\n')
                file.write(word[:-1] + 'らせる' + '\n')
                file.write(word[:-1] + 'らせます' + '\n')
                file.write(word[:-1] + 'らせない' + '\n')
                file.write(word[:-1] + 'らせません' + '\n')
                file.write(word[:-1] + 'ったら' + '\n')
                file.write(word[:-1] + 'りましたら' + '\n')
                file.write(word[:-1] + 'らなかったら' + '\n')
                file.write(word[:-1] + 'りませんでしたら' + '\n')
                file.write(word[:-1] + 'れば' + '\n')
                file.write(word[:-1] + 'らなければ' + '\n')
                file.write(word[:-1] + 'らせられる' + '\n')
                file.write(word[:-1] + 'らせられた' + '\n')
                file.write(word[:-1] + 'られる' + '\n')
                file.write(word[:-1] + 'られます' + '\n')
                file.write(word[:-1] + 'られない' + '\n')
                file.write(word[:-1] + 'られません' + '\n')
                file.write(word + 'な' + '\n')
                file.write(word[:-1] + 'れ' + '\n')
                file.write(word[:-1] + 'りなさい' + '\n')
                file.write(word[:-1] + 'れない' + '\n')
                file.write(word[:-1] + 'れません' + '\n')
                file.write(word[:-1] + 'れる' + '\n')
                file.write(word[:-1] + 'れます' + '\n')
            elif word[-1] == 'む':
                file.write(word[:-1] + 'んで' + '\n')
                file.write(word[:-1] + 'んでなきゃ' + '\n')
                file.write(word[:-1] + 'んでも' + '\n')
                file.write(word[:-1] + 'んでくれる' + '\n')
                file.write(word[:-1] + 'んでくれませんか' + '\n')
                file.write(word[:-1] + 'んでもいいですか' + '\n')
                file.write(word[:-1] + 'んではいけない' + '\n')
                file.write(word[:-1] + 'んではいけません' + '\n')
                file.write(word + '\n')
                file.write(word[:-1] + 'みます' + '\n')
                file.write(word[:-1] + 'みません' + '\n')
                file.write(word[:-1] + 'まない' + '\n')
                file.write(word[:-1] + 'んだ' + '\n')
                file.write(word[:-1] + 'みました' + '\n')
                file.write(word[:-1] + 'みませんでした' + '\n')
                file.write(word[:-1] + 'まなかった' + '\n')
                file.write(word[:-1] + 'んでいる' + '\n')
                file.write(word[:-1] + 'んでる' + '\n')
                file.write(word[:-1] + 'んでいます' + '\n')
                file.write(word[:-1] + 'んでます' + '\n')
                file.write(word[:-1] + 'んでいない' + '\n')
                file.write(word[:-1] + 'んでない' + '\n')
                file.write(word[:-1] + 'んでいません' + '\n')
                file.write(word[:-1] + 'んでません' + '\n')
                file.write(word[:-1] + 'んでいた' + '\n')
                file.write(word[:-1] + 'んでた' + '\n')
                file.write(word[:-1] + 'んでいました' + '\n')
                file.write(word[:-1] + 'んでました' + '\n')
                file.write(word[:-1] + 'んでいなかった' + '\n')
                file.write(word[:-1] + 'んでなかった' + '\n')
                file.write(word[:-1] + 'んでいませんでした' + '\n')
                file.write(word[:-1] + 'んでませんでした' + '\n')
                file.write(word[:-1] + 'み' + '\n')
                file.write(word[:-1] + 'みたい' + '\n')
                file.write(word[:-1] + 'もう' + '\n')
                file.write(word[:-1] + 'みましょう' + '\n')
                file.write(word[:-1] + 'まないだろう' + '\n')
                file.write(word[:-1] + 'まないでしょう' + '\n')
                file.write(word[:-1] + 'んだろう' + '\n')
                file.write(word[:-1] + 'んだでしょう' + '\n')
                file.write(word[:-1] + 'まなかっただろう' + '\n')
                file.write(word[:-1] + 'まなかったでしょう' + '\n')
                file.write(word[:-1] + 'んでください' + '\n')
                file.write(word[:-1] + 'まないでください' + '\n')
                file.write(word[:-1] + 'ませる' + '\n')
                file.write(word[:-1] + 'ませます' + '\n')
                file.write(word[:-1] + 'ませない' + '\n')
                file.write(word[:-1] + 'ませません' + '\n')
                file.write(word[:-1] + 'んだら' + '\n')
                file.write(word[:-1] + 'みましたら' + '\n')
                file.write(word[:-1] + 'まなかったら' + '\n')
                file.write(word[:-1] + 'みませんでしたら' + '\n')
                file.write(word[:-1] + 'めば' + '\n')
                file.write(word[:-1] + 'まなければ' + '\n')
                file.write(word[:-1] + 'ませられる' + '\n')
                file.write(word[:-1] + 'ませられた' + '\n')
                file.write(word[:-1] + 'まれる' + '\n')
                file.write(word[:-1] + 'まれます' + '\n')
                file.write(word[:-1] + 'まれない' + '\n')
                file.write(word[:-1] + 'まれません' + '\n')
                file.write(word + 'な' + '\n')
                file.write(word[:-1] + 'め' + '\n')
                file.write(word[:-1] + 'みなさい' + '\n')
                file.write(word[:-1] + 'めない' + '\n')
                file.write(word[:-1] + 'めません' + '\n')
                file.write(word[:-1] + 'める' + '\n')
                file.write(word[:-1] + 'めます' + '\n')
            elif word[-1] == 'ぶ':
                file.write(word[:-1] + 'んで' + '\n')
                file.write(word[:-1] + 'んでなきゃ' + '\n')
                file.write(word[:-1] + 'んでも' + '\n')
                file.write(word[:-1] + 'んでくれる' + '\n')
                file.write(word[:-1] + 'んでくれませんか' + '\n')
                file.write(word[:-1] + 'んでもいいですか' + '\n')
                file.write(word[:-1] + 'んではいけない' + '\n')
                file.write(word[:-1] + 'んではいけません' + '\n')
                file.write(word + '\n')
                file.write(word[:-1] + 'びます' + '\n')
                file.write(word[:-1] + 'びません' + '\n')
                file.write(word[:-1] + 'ばない' + '\n')
                file.write(word[:-1] + 'んだ' + '\n')
                file.write(word[:-1] + 'びました' + '\n')
                file.write(word[:-1] + 'びませんでした' + '\n')
                file.write(word[:-1] + 'ばなかった' + '\n')
                file.write(word[:-1] + 'んでいる' + '\n')
                file.write(word[:-1] + 'んでる' + '\n')
                file.write(word[:-1] + 'んでいます' + '\n')
                file.write(word[:-1] + 'んでます' + '\n')
                file.write(word[:-1] + 'んでいない' + '\n')
                file.write(word[:-1] + 'んでない' + '\n')
                file.write(word[:-1] + 'んでいません' + '\n')
                file.write(word[:-1] + 'んでません' + '\n')
                file.write(word[:-1] + 'んでいた' + '\n')
                file.write(word[:-1] + 'んでた' + '\n')
                file.write(word[:-1] + 'んでいました' + '\n')
                file.write(word[:-1] + 'んでました' + '\n')
                file.write(word[:-1] + 'んでいなかった' + '\n')
                file.write(word[:-1] + 'んでなかった' + '\n')
                file.write(word[:-1] + 'んでいませんでした' + '\n')
                file.write(word[:-1] + 'んでませんでした' + '\n')
                file.write(word[:-1] + 'び' + '\n')
                file.write(word[:-1] + 'びたい' + '\n')
                file.write(word[:-1] + 'ぼう' + '\n')
                file.write(word[:-1] + 'びましょう' + '\n')
                file.write(word[:-1] + 'ばないだろう' + '\n')
                file.write(word[:-1] + 'ばないでしょう' + '\n')
                file.write(word[:-1] + 'んだろう' + '\n')
                file.write(word[:-1] + 'んだでしょう' + '\n')
                file.write(word[:-1] + 'ばなかっただろう' + '\n')
                file.write(word[:-1] + 'ばなかったでしょう' + '\n')
                file.write(word[:-1] + 'んでください' + '\n')
                file.write(word[:-1] + 'ばないでください' + '\n')
                file.write(word[:-1] + 'ばせる' + '\n')
                file.write(word[:-1] + 'ばせます' + '\n')
                file.write(word[:-1] + 'ばせない' + '\n')
                file.write(word[:-1] + 'ばせません' + '\n')
                file.write(word[:-1] + 'んだら' + '\n')
                file.write(word[:-1] + 'びましたら' + '\n')
                file.write(word[:-1] + 'ばなかったら' + '\n')
                file.write(word[:-1] + 'びませんでしたら' + '\n')
                file.write(word[:-1] + 'べば' + '\n')
                file.write(word[:-1] + 'ばなければ' + '\n')
                file.write(word[:-1] + 'ばせられる' + '\n')
                file.write(word[:-1] + 'ばせられた' + '\n')
                file.write(word[:-1] + 'ばれる' + '\n')
                file.write(word[:-1] + 'ばれます' + '\n')
                file.write(word[:-1] + 'ばれない' + '\n')
                file.write(word[:-1] + 'ばれません' + '\n')
                file.write(word + 'な' + '\n')
                file.write(word[:-1] + 'べ' + '\n')
                file.write(word[:-1] + 'びなさい' + '\n')
                file.write(word[:-1] + 'べない' + '\n')
                file.write(word[:-1] + 'べません' + '\n')
                file.write(word[:-1] + 'べる' + '\n')
                file.write(word[:-1] + 'べます' + '\n')
            elif word[-1] == 'ぬ':
                file.write(word[:-1] + 'んで' + '\n')
                file.write(word[:-1] + 'んでなきゃ' + '\n')
                file.write(word[:-1] + 'んでも' + '\n')
                file.write(word[:-1] + 'んでくれる' + '\n')
                file.write(word[:-1] + 'んでくれませんか' + '\n')
                file.write(word[:-1] + 'んでもいいですか' + '\n')
                file.write(word[:-1] + 'んではいけない' + '\n')
                file.write(word[:-1] + 'んではいけません' + '\n')
                file.write(word + '\n')
                file.write(word[:-1] + 'にます' + '\n')
                file.write(word[:-1] + 'にません' + '\n')
                file.write(word[:-1] + 'なない' + '\n')
                file.write(word[:-1] + 'んだ' + '\n')
                file.write(word[:-1] + 'にました' + '\n')
                file.write(word[:-1] + 'にませんでした' + '\n')
                file.write(word[:-1] + 'ななかった' + '\n')
                file.write(word[:-1] + 'んでいる' + '\n')
                file.write(word[:-1] + 'んでる' + '\n')
                file.write(word[:-1] + 'んでいます' + '\n')
                file.write(word[:-1] + 'んでます' + '\n')
                file.write(word[:-1] + 'んでいない' + '\n')
                file.write(word[:-1] + 'んでない' + '\n')
                file.write(word[:-1] + 'んでいません' + '\n')
                file.write(word[:-1] + 'んでません' + '\n')
                file.write(word[:-1] + 'んでいた' + '\n')
                file.write(word[:-1] + 'んでた' + '\n')
                file.write(word[:-1] + 'んでいました' + '\n')
                file.write(word[:-1] + 'んでました' + '\n')
                file.write(word[:-1] + 'んでいなかった' + '\n')
                file.write(word[:-1] + 'んでなかった' + '\n')
                file.write(word[:-1] + 'んでいませんでした' + '\n')
                file.write(word[:-1] + 'んでませんでした' + '\n')
                file.write(word[:-1] + 'に' + '\n')
                file.write(word[:-1] + 'にたい' + '\n')
                file.write(word[:-1] + 'のう' + '\n')
                file.write(word[:-1] + 'にましょう' + '\n')
                file.write(word[:-1] + 'なないだろう' + '\n')
                file.write(word[:-1] + 'なないでしょう' + '\n')
                file.write(word[:-1] + 'んだろう' + '\n')
                file.write(word[:-1] + 'んだでしょう' + '\n')
                file.write(word[:-1] + 'ななかっただろう' + '\n')
                file.write(word[:-1] + 'ななかったでしょう' + '\n')
                file.write(word[:-1] + 'んでください' + '\n')
                file.write(word[:-1] + 'なないでください' + '\n')
                file.write(word[:-1] + 'なせる' + '\n')
                file.write(word[:-1] + 'なせます' + '\n')
                file.write(word[:-1] + 'なせない' + '\n')
                file.write(word[:-1] + 'なせません' + '\n')
                file.write(word[:-1] + 'んだら' + '\n')
                file.write(word[:-1] + 'にましたら' + '\n')
                file.write(word[:-1] + 'ななかったら' + '\n')
                file.write(word[:-1] + 'にませんでしたら' + '\n')
                file.write(word[:-1] + 'ねば' + '\n')
                file.write(word[:-1] + 'ななければ' + '\n')
                file.write(word[:-1] + 'なせられる' + '\n')
                file.write(word[:-1] + 'なせられた' + '\n')
                file.write(word[:-1] + 'なれる' + '\n')
                file.write(word[:-1] + 'なれます' + '\n')
                file.write(word[:-1] + 'なれない' + '\n')
                file.write(word[:-1] + 'なれません' + '\n')
                file.write(word + 'な' + '\n')
                file.write(word[:-1] + 'ね' + '\n')
                file.write(word[:-1] + 'になさい' + '\n')
                file.write(word[:-1] + 'ねない' + '\n')
                file.write(word[:-1] + 'ねません' + '\n')
                file.write(word[:-1] + 'ねる' + '\n')
                file.write(word[:-1] + 'ねます' + '\n')
            elif word[-1] == 'く':
                file.write(word[:-1] + 'いて' + '\n')
                file.write(word[:-1] + 'いてなきゃ' + '\n')
                file.write(word[:-1] + 'いても' + '\n')
                file.write(word[:-1] + 'いてくれる' + '\n')
                file.write(word[:-1] + 'いてくれませんか' + '\n')
                file.write(word[:-1] + 'いてもいいですか' + '\n')
                file.write(word[:-1] + 'いてはいけない' + '\n')
                file.write(word[:-1] + 'いてはいけません' + '\n')
                file.write(word + '\n')
                file.write(word[:-1] + 'きます' + '\n')
                file.write(word[:-1] + 'きません' + '\n')
                file.write(word[:-1] + 'かない' + '\n')
                file.write(word[:-1] + 'いた' + '\n')
                file.write(word[:-1] + 'きました' + '\n')
                file.write(word[:-1] + 'きませんでした' + '\n')
                file.write(word[:-1] + 'かなかった' + '\n')
                file.write(word[:-1] + 'いている' + '\n')
                file.write(word[:-1] + 'いてる' + '\n')
                file.write(word[:-1] + 'いています' + '\n')
                file.write(word[:-1] + 'いてます' + '\n')
                file.write(word[:-1] + 'いていない' + '\n')
                file.write(word[:-1] + 'いてない' + '\n')
                file.write(word[:-1] + 'いていません' + '\n')
                file.write(word[:-1] + 'いてません' + '\n')
                file.write(word[:-1] + 'いていた' + '\n')
                file.write(word[:-1] + 'いてた' + '\n')
                file.write(word[:-1] + 'いていました' + '\n')
                file.write(word[:-1] + 'いてました' + '\n')
                file.write(word[:-1] + 'いていなかった' + '\n')
                file.write(word[:-1] + 'いてなかった' + '\n')
                file.write(word[:-1] + 'いていませんでした' + '\n')
                file.write(word[:-1] + 'いてませんでした' + '\n')
                file.write(word[:-1] + 'き' + '\n')
                file.write(word[:-1] + 'きたい' + '\n')
                file.write(word[:-1] + 'こう' + '\n')
                file.write(word[:-1] + 'きましょう' + '\n')
                file.write(word[:-1] + 'かないだろう' + '\n')
                file.write(word[:-1] + 'かないでしょう' + '\n')
                file.write(word[:-1] + 'いたろう' + '\n')
                file.write(word[:-1] + 'いたでしょう' + '\n')
                file.write(word[:-1] + 'かなかっただろう' + '\n')
                file.write(word[:-1] + 'かなかったでしょう' + '\n')
                file.write(word[:-1] + 'いてください' + '\n')
                file.write(word[:-1] + 'かないでください' + '\n')
                file.write(word[:-1] + 'かせる' + '\n')
                file.write(word[:-1] + 'かせます' + '\n')
                file.write(word[:-1] + 'かせない' + '\n')
                file.write(word[:-1] + 'かせません' + '\n')
                file.write(word[:-1] + 'いたら' + '\n')
                file.write(word[:-1] + 'きましたら' + '\n')
                file.write(word[:-1] + 'かなかったら' + '\n')
                file.write(word[:-1] + 'きませんでしたら' + '\n')
                file.write(word[:-1] + 'けば' + '\n')
                file.write(word[:-1] + 'かなければ' + '\n')
                file.write(word[:-1] + 'かせられる' + '\n')
                file.write(word[:-1] + 'かせられた' + '\n')
                file.write(word[:-1] + 'かれる' + '\n')
                file.write(word[:-1] + 'かれます' + '\n')
                file.write(word[:-1] + 'かれない' + '\n')
                file.write(word[:-1] + 'かれません' + '\n')
                file.write(word + 'な' + '\n')
                file.write(word[:-1] + 'け' + '\n')
                file.write(word[:-1] + 'きなさい' + '\n')
                file.write(word[:-1] + 'けない' + '\n')
                file.write(word[:-1] + 'けません' + '\n')
                file.write(word[:-1] + 'ける' + '\n')
                file.write(word[:-1] + 'けます' + '\n')
            elif word[-1] == 'ぐ':
                file.write(word[:-1] + 'いで' + '\n')
                file.write(word[:-1] + 'いでなきゃ' + '\n')
                file.write(word[:-1] + 'いでも' + '\n')
                file.write(word[:-1] + 'いでくれる' + '\n')
                file.write(word[:-1] + 'いでくれませんか' + '\n')
                file.write(word[:-1] + 'いでもいいですか' + '\n')
                file.write(word[:-1] + 'いではいけない' + '\n')
                file.write(word[:-1] + 'いではいけません' + '\n')
                file.write(word + '\n')
                file.write(word[:-1] + 'ぎます' + '\n')
                file.write(word[:-1] + 'ぎません' + '\n')
                file.write(word[:-1] + 'がない' + '\n')
                file.write(word[:-1] + 'いだ' + '\n')
                file.write(word[:-1] + 'ぎました' + '\n')
                file.write(word[:-1] + 'ぎませんでした' + '\n')
                file.write(word[:-1] + 'がなかった' + '\n')
                file.write(word[:-1] + 'いでいる' + '\n')
                file.write(word[:-1] + 'いでる' + '\n')
                file.write(word[:-1] + 'いでいます' + '\n')
                file.write(word[:-1] + 'いでます' + '\n')
                file.write(word[:-1] + 'いでいない' + '\n')
                file.write(word[:-1] + 'いでない' + '\n')
                file.write(word[:-1] + 'いでいません' + '\n')
                file.write(word[:-1] + 'いでません' + '\n')
                file.write(word[:-1] + 'いでいた' + '\n')
                file.write(word[:-1] + 'いでた' + '\n')
                file.write(word[:-1] + 'いでいました' + '\n')
                file.write(word[:-1] + 'いでました' + '\n')
                file.write(word[:-1] + 'いでいなかった' + '\n')
                file.write(word[:-1] + 'いでなかった' + '\n')
                file.write(word[:-1] + 'いでいませんでした' + '\n')
                file.write(word[:-1] + 'いでませんでした' + '\n')
                file.write(word[:-1] + 'ぎ' + '\n')
                file.write(word[:-1] + 'ぎたい' + '\n')
                file.write(word[:-1] + 'ごう' + '\n')
                file.write(word[:-1] + 'ぎましょう' + '\n')
                file.write(word[:-1] + 'がないだろう' + '\n')
                file.write(word[:-1] + 'がないでしょう' + '\n')
                file.write(word[:-1] + 'いだろう' + '\n')
                file.write(word[:-1] + 'いたでしょう' + '\n')
                file.write(word[:-1] + 'がなかっただろう' + '\n')
                file.write(word[:-1] + 'がなかったでしょう' + '\n')
                file.write(word[:-1] + 'いでください' + '\n')
                file.write(word[:-1] + 'がないでください' + '\n')
                file.write(word[:-1] + 'がせる' + '\n')
                file.write(word[:-1] + 'がせます' + '\n')
                file.write(word[:-1] + 'がせない' + '\n')
                file.write(word[:-1] + 'がせません' + '\n')
                file.write(word[:-1] + 'いだら' + '\n')
                file.write(word[:-1] + 'ぎましたら' + '\n')
                file.write(word[:-1] + 'がなかったら' + '\n')
                file.write(word[:-1] + 'ぎませんでしたら' + '\n')
                file.write(word[:-1] + 'げば' + '\n')
                file.write(word[:-1] + 'がなければ' + '\n')
                file.write(word[:-1] + 'がせられる' + '\n')
                file.write(word[:-1] + 'がせられた' + '\n')
                file.write(word[:-1] + 'がれる' + '\n')
                file.write(word[:-1] + 'がれます' + '\n')
                file.write(word[:-1] + 'がれない' + '\n')
                file.write(word[:-1] + 'がれません' + '\n')
                file.write(word + 'な' + '\n')
                file.write(word[:-1] + 'げ' + '\n')
                file.write(word[:-1] + 'ぎなさい' + '\n')
                file.write(word[:-1] + 'げない' + '\n')
                file.write(word[:-1] + 'げません' + '\n')
                file.write(word[:-1] + 'げる' + '\n')
                file.write(word[:-1] + 'げます' + '\n')
            elif word[-1] == 'す':
                file.write(word[:-1] + 'して' + '\n')
                file.write(word[:-1] + 'してなきゃ' + '\n')
                file.write(word[:-1] + 'しても' + '\n')
                file.write(word[:-1] + 'してくれる' + '\n')
                file.write(word[:-1] + 'してくれませんか' + '\n')
                file.write(word[:-1] + 'してもいいですか' + '\n')
                file.write(word[:-1] + 'してはいけない' + '\n')
                file.write(word[:-1] + 'してはいけません' + '\n')
                file.write(word + '\n')
                file.write(word[:-1] + 'します' + '\n')
                file.write(word[:-1] + 'しません' + '\n')
                file.write(word[:-1] + 'さない' + '\n')
                file.write(word[:-1] + 'した' + '\n')
                file.write(word[:-1] + 'しました' + '\n')
                file.write(word[:-1] + 'しませんでした' + '\n')
                file.write(word[:-1] + 'さなかった' + '\n')
                file.write(word[:-1] + 'している' + '\n')
                file.write(word[:-1] + 'してる' + '\n')
                file.write(word[:-1] + 'しています' + '\n')
                file.write(word[:-1] + 'してます' + '\n')
                file.write(word[:-1] + 'していない' + '\n')
                file.write(word[:-1] + 'してない' + '\n')
                file.write(word[:-1] + 'していません' + '\n')
                file.write(word[:-1] + 'してません' + '\n')
                file.write(word[:-1] + 'していた' + '\n')
                file.write(word[:-1] + 'してた' + '\n')
                file.write(word[:-1] + 'していました' + '\n')
                file.write(word[:-1] + 'してました' + '\n')
                file.write(word[:-1] + 'していなかった' + '\n')
                file.write(word[:-1] + 'してなかった' + '\n')
                file.write(word[:-1] + 'していませんでした' + '\n')
                file.write(word[:-1] + 'してませんでした' + '\n')
                file.write(word[:-1] + 'し' + '\n')
                file.write(word[:-1] + 'したい' + '\n')
                file.write(word[:-1] + 'そう' + '\n')
                file.write(word[:-1] + 'しましょう' + '\n')
                file.write(word[:-1] + 'さないだろう' + '\n')
                file.write(word[:-1] + 'さないでしょう' + '\n')
                file.write(word[:-1] + 'したろう' + '\n')
                file.write(word[:-1] + 'したでしょう' + '\n')
                file.write(word[:-1] + 'さなかっただろう' + '\n')
                file.write(word[:-1] + 'さなかったでしょう' + '\n')
                file.write(word[:-1] + 'してください' + '\n')
                file.write(word[:-1] + 'さないでください' + '\n')
                file.write(word[:-1] + 'させる' + '\n')
                file.write(word[:-1] + 'させます' + '\n')
                file.write(word[:-1] + 'させない' + '\n')
                file.write(word[:-1] + 'させません' + '\n')
                file.write(word[:-1] + 'したら' + '\n')
                file.write(word[:-1] + 'しましたら' + '\n')
                file.write(word[:-1] + 'さなかったら' + '\n')
                file.write(word[:-1] + 'しませんでしたら' + '\n')
                file.write(word[:-1] + 'せば' + '\n')
                file.write(word[:-1] + 'さなければ' + '\n')
                file.write(word[:-1] + 'させられる' + '\n')
                file.write(word[:-1] + 'させられた' + '\n')
                file.write(word[:-1] + 'される' + '\n')
                file.write(word[:-1] + 'されます' + '\n')
                file.write(word[:-1] + 'されない' + '\n')
                file.write(word[:-1] + 'されません' + '\n')
                file.write(word + 'な' + '\n')
                file.write(word[:-1] + 'せ' + '\n')
                file.write(word[:-1] + 'しなさい' + '\n')
                file.write(word[:-1] + 'せない' + '\n')
                file.write(word[:-1] + 'せません' + '\n')
                file.write(word[:-1] + 'せる' + '\n')
                file.write(word[:-1] + 'せます' + '\n')
            else:
                file.write("Error: word is not a verb or adjective" + '\n')
        number_of_lines += 1

# Read from Japanese__Export__2.txt file
j_exp_file = open('Japanese__Export__2.txt', 'r')
file_content = j_exp_file.read()
lines = file_content.split('\n')
j_exp_file.close()

# Mode 'a' appends lines to the end of the file
with open('conjugated.txt', 'a') as file:
    for line in lines:
        if re.search("^.+\t", line):
            word = re.findall("^.+\t", line)[0][0:-1]
            file.write(word[:-1] + 'て' + '\n')
            file.write(word[:-1] + 'てなきゃ' + '\n')
            file.write(word[:-1] + 'ても' + '\n')
            file.write(word[:-1] + 'てくれる' + '\n')
            file.write(word[:-1] + 'てくれませんか' + '\n')
            file.write(word[:-1] + 'てもいいですか' + '\n')
            file.write(word[:-1] + 'てはいけない' + '\n')
            file.write(word[:-1] + 'てはいけません' + '\n')
            file.write(word + '\n')
            file.write(word[:-1] + 'ます' + '\n')
            file.write(word[:-1] + 'ない' + '\n')
            file.write(word[:-1] + 'ません' + '\n')
            file.write(word[:-1] + 'た' + '\n')
            file.write(word[:-1] + 'ました' + '\n')
            file.write(word[:-1] + 'なかった' + '\n')
            file.write(word[:-1] + 'ませんでした' + '\n')
            file.write(word[:-1] + 'ている' + '\n')
            file.write(word[:-1] + 'てる' + '\n')
            file.write(word[:-1] + 'ています' + '\n')
            file.write(word[:-1] + 'てます' + '\n')
            file.write(word[:-1] + 'ていない' + '\n')
            file.write(word[:-1] + 'てない' + '\n')
            file.write(word[:-1] + 'ていません' + '\n')
            file.write(word[:-1] + 'てません' + '\n')
            file.write(word[:-1] + 'ていた' + '\n')
            file.write(word[:-1] + 'てた' + '\n')
            file.write(word[:-1] + 'ていました' + '\n')
            file.write(word[:-1] + 'てました' + '\n')
            file.write(word[:-1] + 'ていなかった' + '\n')
            file.write(word[:-1] + 'てなかった' + '\n')
            file.write(word[:-1] + 'ていませんでした' + '\n')
            file.write(word[:-1] + 'てませんでした' + '\n')
            file.write(word[:-1] + '\n')
            file.write(word[:-1] + 'たい' + '\n')
            file.write(word[:-1] + 'よう' + '\n')
            file.write(word[:-1] + 'ましょう' + '\n')
            file.write(word[:-1] + 'ないだろう' + '\n')
            file.write(word[:-1] + 'ないでしょう' + '\n')
            file.write(word[:-1] + 'たろう' + '\n')
            file.write(word[:-1] + 'たでしょう' + '\n')
            file.write(word[:-1] + 'てください' + '\n')
            file.write(word[:-1] + 'ないでください' + '\n')
            file.write(word[:-1] + 'させる' + '\n')
            file.write(word[:-1] + 'させます' + '\n')
            file.write(word[:-1] + 'させない' + '\n')
            file.write(word[:-1] + 'させません' + '\n')
            file.write(word[:-1] + 'たら' + '\n')
            file.write(word[:-1] + 'ましたら' + '\n')
            file.write(word[:-1] + 'なかったら' + '\n')
            file.write(word[:-1] + 'ませんでしたら' + '\n')
            file.write(word[:-1] + 'れば' + '\n')
            file.write(word[:-1] + 'なければ' + '\n')
            file.write(word[:-1] + 'させられる' + '\n')
            file.write(word[:-1] + 'させられた' + '\n')
            file.write(word[:-1] + 'られる' + '\n')
            file.write(word[:-1] + 'られます' + '\n')
            file.write(word[:-1] + 'られない' + '\n')
            file.write(word[:-1] + 'られません' + '\n')
            file.write(word + 'な' + '\n')
            file.write(word[:-1] + 'ろ' + '\n')
            file.write(word[:-1] + 'なさい' + '\n')
        number_of_lines += 1

# Choose words at random and print them to the console
for i in range(0, int(sys.argv[1])):
    print(linecache.getline("conjugated.txt", random.randint(1, number_of_lines))) 