apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    autoscaling.alpha.kubernetes.io/conditions: '[{...}]'
    creationTimestamp: "2020-04-26T23:46:10Z"
    name: project_name
    namespace: namespace_name
    resourceVersion: "23435345"
    selfLink: /apis/autoscaling/v1/namespaces/namespace_name/horizontalpodautoscalers/project_name
    uid: 345u48905-3445-34343-349343
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    name: project_name
  targetCPUUtilizationPercentage: 90
status:
  currentReplicas: 2
  desiredReplicas: 0