apiVersion: v1
kind: SecurityContextConstraints
metadata:
  name: security_context_constraint_admin
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- service_account_name
requiredDropCapabilities:
- KILL
- MKNOD
- SYS_CHROOT